{==============================================================================
  CopperBalancing_v4_3_AD26.pas
  Altium Designer DelphiScript

  Copper Balancing generator with multi-layer selection, pattern preview, progress bars and fast bulk removal.

  Key option:
    "Group into component"
      ON  -> generated pads belong to COPPER_BALANCE_TOP/BOTTOM
             (easy bulk removal with RemoveCopperBalance)
      OFF -> every generated pad is a FREE IPCB_Pad (SMD, No Net, no paste/mask opening)
             (can be selected/moved/deleted individually)

  Entry points:
    Start                -> open GUI, select one or more signal layers and generate balancing
    RemoveCopperBalance  -> remove generated objects globally | layer: all supported layers
    FixCopperBalanceMasks -> repair Top/Bottom solder-mask tenting | layer: generated free pads

  IMPORTANT:
    Test | layer: a COPY of the PCB first and run DRC after generation.
==============================================================================}

var
    Board : IPCB_Board;

    { Runtime settings filled by the GUI }
    CB_LAYER_IDS          : array[0..127] of TLayer;
    CB_LAYER_SELECTED     : array[0..127] of Boolean;
    CB_LAYER_CHECKS       : array[0..127] of TCheckBox;
    CB_LAYER_COUNT        : Integer;

    CB_PAD_SIZE_MM        : Double;
    CB_PITCH_X_MM         : Double;
    CB_PITCH_Y_MM         : Double;
    CB_COPPER_CLEAR_MM    : Double;
    CB_EDGE_CLEAR_MM      : Double;

    { 0 = aligned squares, 1 = staggered pads, 2 = staggered circles }
    CB_PATTERN_TYPE       : Integer;

    CB_GROUP_AS_COMPONENT : Boolean;
    CB_REMOVE_REQUESTED   : Boolean;

    { Runtime progress window }
    CB_PROGRESS_FORM      : TForm;
    CB_PROGRESS_BAR       : TProgressBar;
    CB_PROGRESS_LABEL     : TLabel;
    CB_PROGRESS_PERCENT   : TLabel;
    CB_PROGRESS_MAX       : Integer;
    CB_PROGRESS_POS       : Integer;
    CB_PROGRESS_LAST_UI   : Integer;

const
    { Conservative board-edge sampling. Higher = safer but slower. }
    CB_EDGE_SAMPLES       = 24;

    { Holder component names used only in grouped mode. }
    { Markers used to safely identify objects generated by this script. }
    CB_PAD_MARKER         = 'CB_BALANCE';
    CB_HOLDER_MARKER      = 'CB_BALANCE_HOLDER';

    CB_PATTERN_SQUARE     = 0;
    CB_PATTERN_DIAMOND    = 1;
    CB_PATTERN_CIRCLE     = 2;


{------------------------------------------------------------------------------}
procedure CloseProgressWindow(Dummy : Integer);
begin
    if CB_PROGRESS_FORM <> nil then
    begin
        CB_PROGRESS_FORM.Close;
        CB_PROGRESS_FORM.Free;
    end;

    CB_PROGRESS_FORM := nil;
    CB_PROGRESS_BAR := nil;
    CB_PROGRESS_LABEL := nil;
    CB_PROGRESS_PERCENT := nil;

    CB_PROGRESS_MAX := 0;
    CB_PROGRESS_POS := 0;
    CB_PROGRESS_LAST_UI := -1;
end;


{------------------------------------------------------------------------------}
procedure ShowProgressWindow(ATitle, AStatus : String; AMax : Integer);
begin
    CloseProgressWindow(0);

    if AMax <= 0 then
        AMax := 1;

    CB_PROGRESS_MAX := AMax;
    CB_PROGRESS_POS := 0;
    CB_PROGRESS_LAST_UI := -1;

    CB_PROGRESS_FORM := TForm.Create(nil);
    CB_PROGRESS_FORM.Caption := ATitle;
    CB_PROGRESS_FORM.Position := poScreenCenter;
    CB_PROGRESS_FORM.BorderStyle := bsDialog;
    CB_PROGRESS_FORM.ClientWidth := 430;
    CB_PROGRESS_FORM.ClientHeight := 118;

    CB_PROGRESS_LABEL := TLabel.Create(CB_PROGRESS_FORM);
    CB_PROGRESS_LABEL.Parent := CB_PROGRESS_FORM;
    CB_PROGRESS_LABEL.Left := 18;
    CB_PROGRESS_LABEL.Top := 16;
    CB_PROGRESS_LABEL.Width := 390;
    CB_PROGRESS_LABEL.Caption := AStatus;

    CB_PROGRESS_BAR := TProgressBar.Create(CB_PROGRESS_FORM);
    CB_PROGRESS_BAR.Parent := CB_PROGRESS_FORM;
    CB_PROGRESS_BAR.Left := 18;
    CB_PROGRESS_BAR.Top := 45;
    CB_PROGRESS_BAR.Width := 394;
    CB_PROGRESS_BAR.Height := 22;
    CB_PROGRESS_BAR.Min := 0;
    CB_PROGRESS_BAR.Max := CB_PROGRESS_MAX;
    CB_PROGRESS_BAR.Position := 0;

    CB_PROGRESS_PERCENT := TLabel.Create(CB_PROGRESS_FORM);
    CB_PROGRESS_PERCENT.Parent := CB_PROGRESS_FORM;
    CB_PROGRESS_PERCENT.Left := 18;
    CB_PROGRESS_PERCENT.Top := 80;
    CB_PROGRESS_PERCENT.Width := 394;
    CB_PROGRESS_PERCENT.Caption := '0%';

    CB_PROGRESS_FORM.Show;
    CB_PROGRESS_FORM.Update;
    CB_PROGRESS_BAR.Update;
end;


{------------------------------------------------------------------------------}
procedure SetProgressStatus(AStatus : String);
begin
    if CB_PROGRESS_LABEL = nil then Exit;

    CB_PROGRESS_LABEL.Caption := AStatus;
    CB_PROGRESS_LABEL.Update;
end;


{------------------------------------------------------------------------------}
procedure UpdateProgress(AIncrement : Integer);
var
    Percent : Integer;
begin
    if CB_PROGRESS_BAR = nil then Exit;

    CB_PROGRESS_POS := CB_PROGRESS_POS + AIncrement;

    if CB_PROGRESS_POS > CB_PROGRESS_MAX then
        CB_PROGRESS_POS := CB_PROGRESS_MAX;

    if CB_PROGRESS_MAX > 0 then
        Percent := (CB_PROGRESS_POS * 100) div CB_PROGRESS_MAX
    else
        Percent := 100;

    { Refresh only when the visible percentage changes.
      This keeps generation fast | layer: dense patterns. }
    if Percent <> CB_PROGRESS_LAST_UI then
    begin
        CB_PROGRESS_LAST_UI := Percent;

        CB_PROGRESS_BAR.Position := CB_PROGRESS_POS;
        CB_PROGRESS_BAR.Update;

        if CB_PROGRESS_PERCENT <> nil then
        begin
            CB_PROGRESS_PERCENT.Caption :=
                IntToStr(Percent) + '%   (' +
                IntToStr(CB_PROGRESS_POS) + ' / ' +
                IntToStr(CB_PROGRESS_MAX) + ')';
            CB_PROGRESS_PERCENT.Update;
        end;

        if CB_PROGRESS_FORM <> nil then
            CB_PROGRESS_FORM.Update;
    end;
end;


{------------------------------------------------------------------------------}
procedure FinishProgress(Dummy : Integer);
begin
    if CB_PROGRESS_BAR <> nil then
    begin
        CB_PROGRESS_POS := CB_PROGRESS_MAX;
        CB_PROGRESS_BAR.Position := CB_PROGRESS_MAX;
        CB_PROGRESS_BAR.Update;
    end;

    if CB_PROGRESS_PERCENT <> nil then
    begin
        CB_PROGRESS_PERCENT.Caption := '100%';
        CB_PROGRESS_PERCENT.Update;
    end;

    if CB_PROGRESS_FORM <> nil then
        CB_PROGRESS_FORM.Update;
end;


{------------------------------------------------------------------------------}
procedure InitDefaults(Dummy : Integer);
var
    I : Integer;
begin
    CB_LAYER_COUNT := 0;

    for I := 0 to 127 do
    begin
        CB_LAYER_SELECTED[I] := False;
        CB_LAYER_CHECKS[I] := nil;
    end;

    CB_PAD_SIZE_MM        := 1.00;
    CB_PITCH_X_MM         := 2.00;
    CB_PITCH_Y_MM         := 2.00;

    CB_COPPER_CLEAR_MM    := 0.50;
    CB_EDGE_CLEAR_MM      := 0.50;

    { Default = current staggered pad pattern. }
    CB_PATTERN_TYPE       := CB_PATTERN_DIAMOND;

    { OFF = individual free pads, easy single-item Delete. }
    CB_GROUP_AS_COMPONENT := False;

    CB_REMOVE_REQUESTED   := False;

    CB_PROGRESS_FORM := nil;
    CB_PROGRESS_BAR := nil;
    CB_PROGRESS_LABEL := nil;
    CB_PROGRESS_PERCENT := nil;
    CB_PROGRESS_MAX := 0;
    CB_PROGRESS_POS := 0;
    CB_PROGRESS_LAST_UI := -1;
end;


{------------------------------------------------------------------------------}
function PopulateCopperLayerChecks(Scroll : TScrollBox) : Integer;
var
    Stack        : IPCB_LayerStack;
    LayerObj     : IPCB_LayerObject;
    Layer        : TLayer;
    Ch           : TCheckBox;
    YPos         : Integer;
    CurrentFound : Boolean;
    I            : Integer;
begin
    Result := 0;
    CB_LAYER_COUNT := 0;
    CurrentFound := False;
    YPos := 8;

    Stack := Board.LayerStack;
    if Stack = nil then Exit;

    { AD 26.9.x-compatible signal-layer enumeration.
      eTopLayer..eBottomLayer covers positive signal copper layers.
      Negative Internal Plane layers are outside this range and are omitted. }
    for Layer := eTopLayer to eBottomLayer do
    begin
        LayerObj := Stack.LayerObject[Layer];

        if LayerObj <> nil then
        begin
            if LayerObj.IsInLayerStack then
            begin
                if CB_LAYER_COUNT <= 127 then
                begin
                    CB_LAYER_IDS[CB_LAYER_COUNT] := Layer;

                    Ch := TCheckBox.Create(Scroll);
                    Ch.Parent := Scroll;
                    Ch.Left := 8;
                    Ch.Top := YPos;
                    Ch.Width := 210;
                    Ch.Caption := LayerObj.Name;
                    Ch.Checked := False;

                    if Layer = Board.CurrentLayer then
                    begin
                        Ch.Checked := True;
                        CurrentFound := True;
                    end;

                    CB_LAYER_CHECKS[CB_LAYER_COUNT] := Ch;

                    Inc(CB_LAYER_COUNT);
                    Inc(Result);

                    YPos := YPos + 24;
                end;
            end;
        end;
    end;

    { If current layer is not a signal copper layer, select the first one. }
    if not CurrentFound then
    begin
        if CB_LAYER_COUNT > 0 then
            CB_LAYER_CHECKS[0].Checked := True;
    end;

    { Clear selection state before reading the dialog result. }
    for I := 0 to CB_LAYER_COUNT - 1 do
        CB_LAYER_SELECTED[I] := False;
end;


{------------------------------------------------------------------------------}
function IsOuterLayer(ALayer : TLayer) : Boolean;
begin
    Result := False;

    if ALayer = eTopLayer then
    begin
        Result := True;
        Exit;
    end;

    if ALayer = eBottomLayer then
    begin
        Result := True;
        Exit;
    end;
end;


{------------------------------------------------------------------------------}
function PatternName(Dummy : Integer) : String;
begin
    Result := 'Diamonds';

    if CB_PATTERN_TYPE = CB_PATTERN_SQUARE then
    begin
        Result := 'Squares';
        Exit;
    end;

    if CB_PATTERN_TYPE = CB_PATTERN_CIRCLE then
    begin
        Result := 'Circles';
        Exit;
    end;
end;


{------------------------------------------------------------------------------}
function ShowSettingsDialog(Dummy : Integer) : Boolean;
var
    F             : TForm;
    L             : TLabel;
    Scroll        : TScrollBox;
    GbPattern     : TGroupBox;

    EdSize        : TEdit;
    EdPitchX      : TEdit;
    EdPitchY      : TEdit;
    EdCopperClear : TEdit;
    EdEdgeClear   : TEdit;

    RbSquare      : TRadioButton;
    RbDiamond     : TRadioButton;
    RbCircle      : TRadioButton;

    PvSquare      : TLabel;
    PvDiamond     : TLabel;
    PvCircle      : TLabel;

    ChGroup       : TCheckBox;

    BtnGenerate   : TButton;
    BtnRemove     : TButton;
    BtnCancel     : TButton;

    R             : Integer;
    I             : Integer;
    SelectedCount : Integer;
begin
    Result := False;
    CB_REMOVE_REQUESTED := False;

    F := TForm.Create(nil);
    Try
        F.Caption := 'Copper Balancing Generator';
        F.Position := poScreenCenter;
        F.BorderStyle := bsDialog;
        F.ClientWidth := 790;
        F.ClientHeight := 610;

        { ================================================================
          LEFT: LAYER CHECKBOXES
          ================================================================ }
        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 18;
        L.Top := 16;
        L.Caption := 'Copper layers - select one or more:';

        Scroll := TScrollBox.Create(F);
        Scroll.Parent := F;
        Scroll.Left := 18;
        Scroll.Top := 40;
        Scroll.Width := 245;
        Scroll.Height := 500;
        Scroll.AutoScroll := True;

        PopulateCopperLayerChecks(Scroll);

        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 18;
        L.Top := 544;
        L.Width := 245;
        L.Width := 245;
        L.Caption := 'Signal layers only. Negative Internal Plane layers are not listed.';

        { ================================================================
          RIGHT: NUMERIC PARAMETERS
          ================================================================ }
        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 290;
        L.Top := 18;
        L.Caption := 'Element size [mm]:';

        EdSize := TEdit.Create(F);
        EdSize.Parent := F;
        EdSize.Left := 515;
        EdSize.Top := 14;
        EdSize.Width := 100;
        EdSize.Text := FloatToStr(CB_PAD_SIZE_MM);

        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 290;
        L.Top := 50;
        L.Caption := 'Horizontal spacing X [mm]:';

        EdPitchX := TEdit.Create(F);
        EdPitchX.Parent := F;
        EdPitchX.Left := 515;
        EdPitchX.Top := 46;
        EdPitchX.Width := 100;
        EdPitchX.Text := FloatToStr(CB_PITCH_X_MM);

        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 290;
        L.Top := 82;
        L.Caption := 'Vertical spacing Y [mm]:';

        EdPitchY := TEdit.Create(F);
        EdPitchY.Parent := F;
        EdPitchY.Left := 515;
        EdPitchY.Top := 78;
        EdPitchY.Width := 100;
        EdPitchY.Text := FloatToStr(CB_PITCH_Y_MM);

        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 290;
        L.Top := 114;
        L.Width := 215;
        L.Caption := 'Clearance from existing copper [mm]:';

        EdCopperClear := TEdit.Create(F);
        EdCopperClear.Parent := F;
        EdCopperClear.Left := 515;
        EdCopperClear.Top := 110;
        EdCopperClear.Width := 100;
        EdCopperClear.Text := FloatToStr(CB_COPPER_CLEAR_MM);

        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 290;
        L.Top := 146;
        L.Width := 215;
        L.Caption := 'Clearance from board edge [mm]:';

        EdEdgeClear := TEdit.Create(F);
        EdEdgeClear.Parent := F;
        EdEdgeClear.Left := 515;
        EdEdgeClear.Top := 142;
        EdEdgeClear.Width := 100;
        EdEdgeClear.Text := FloatToStr(CB_EDGE_CLEAR_MM);

        ChGroup := TCheckBox.Create(F);
        ChGroup.Parent := F;
        ChGroup.Left := 290;
        ChGroup.Top := 182;
        ChGroup.Width := 390;
        ChGroup.Caption := 'Keep generated elements grouped together';
        ChGroup.Checked := CB_GROUP_AS_COMPONENT;

        L := TLabel.Create(F);
        L.Parent := F;
        L.Left := 310;
        L.Top := 205;
        L.Width := 385;
        L.Caption := 'OFF = elements remain independent and can be edited or deleted one by one.';

        { ================================================================
          PATTERN SELECTOR + GRAPHICAL PREVIEW
          ================================================================ }
        GbPattern := TGroupBox.Create(F);
        GbPattern.Parent := F;
        GbPattern.Left := 285;
        GbPattern.Top := 235;
        GbPattern.Width := 480;
        GbPattern.Height := 275;
        GbPattern.Caption := 'Pattern / preview';

        RbSquare := TRadioButton.Create(GbPattern);
        RbSquare.Parent := GbPattern;
        RbSquare.Left := 15;
        RbSquare.Top := 28;
        RbSquare.Width := 110;
        RbSquare.Caption := 'Squares';
        RbSquare.Checked := (CB_PATTERN_TYPE = CB_PATTERN_SQUARE);

        PvSquare := TLabel.Create(GbPattern);
        PvSquare.Parent := GbPattern;
        PvSquare.Left := 135;
        PvSquare.Top := 24;
        PvSquare.Width := 260;
        PvSquare.Height := 48;
        PvSquare.Font.Name := 'Courier New';
        PvSquare.Font.Size := 10;
        PvSquare.Caption :=
            '[ ]   [ ]   [ ]' + #13#10 +
            '[ ]   [ ]   [ ]' + #13#10 +
            '[ ]   [ ]   [ ]';

        RbDiamond := TRadioButton.Create(GbPattern);
        RbDiamond.Parent := GbPattern;
        RbDiamond.Left := 15;
        RbDiamond.Top := 105;
        RbDiamond.Width := 110;
        RbDiamond.Caption := 'Diamonds';
        RbDiamond.Checked := (CB_PATTERN_TYPE = CB_PATTERN_DIAMOND);

        PvDiamond := TLabel.Create(GbPattern);
        PvDiamond.Parent := GbPattern;
        PvDiamond.Left := 135;
        PvDiamond.Top := 92;
        PvDiamond.Width := 260;
        PvDiamond.Height := 60;
        PvDiamond.Font.Name := 'Courier New';
        PvDiamond.Font.Size := 10;
        PvDiamond.Caption :=
            '<>    <>    <>' + #13#10 +
            '   <>    <>    <>' + #13#10 +
            '<>    <>    <>';

        RbCircle := TRadioButton.Create(GbPattern);
        RbCircle.Parent := GbPattern;
        RbCircle.Left := 15;
        RbCircle.Top := 190;
        RbCircle.Width := 110;
        RbCircle.Caption := 'Circles';
        RbCircle.Checked := (CB_PATTERN_TYPE = CB_PATTERN_CIRCLE);

        PvCircle := TLabel.Create(GbPattern);
        PvCircle.Parent := GbPattern;
        PvCircle.Left := 135;
        PvCircle.Top := 177;
        PvCircle.Width := 260;
        PvCircle.Height := 60;
        PvCircle.Font.Name := 'Courier New';
        PvCircle.Font.Size := 10;
        PvCircle.Caption :=
            '(O)   (O)   (O)' + #13#10 +
            '   (O)   (O)   (O)' + #13#10 +
            '(O)   (O)   (O)';

        L := TLabel.Create(GbPattern);
        L.Parent := GbPattern;
        L.Left := 15;
        L.Top := 245;
        L.Width := 395;
        L.Caption := 'Squares = aligned. Diamonds/Circles = every second row shifted by Pitch X / 2.';

        { ================================================================
          ACTION BUTTONS
          ================================================================ }
        BtnRemove := TButton.Create(F);
        BtnRemove.Parent := F;
        BtnRemove.Left := 330;
        BtnRemove.Top := 555;
        BtnRemove.Width := 160;
        BtnRemove.Caption := 'Remove Copper Balancing';
        BtnRemove.ModalResult := mrYes;

        BtnGenerate := TButton.Create(F);
        BtnGenerate.Parent := F;
        BtnGenerate.Left := 590;
        BtnGenerate.Top := 555;
        BtnGenerate.Width := 85;
        BtnGenerate.Caption := 'Generate';
        BtnGenerate.ModalResult := mrOk;
        BtnGenerate.Default := True;

        BtnCancel := TButton.Create(F);
        BtnCancel.Parent := F;
        BtnCancel.Left := 685;
        BtnCancel.Top := 555;
        BtnCancel.Width := 85;
        BtnCancel.Caption := 'Cancel';
        BtnCancel.ModalResult := mrCancel;
        BtnCancel.Cancel := True;

        R := F.ShowModal;

        if R = mrYes then
        begin
            CB_REMOVE_REQUESTED := True;
            Exit;
        end;

        if R <> mrOk then Exit;

        SelectedCount := 0;

        for I := 0 to CB_LAYER_COUNT - 1 do
        begin
            CB_LAYER_SELECTED[I] := CB_LAYER_CHECKS[I].Checked;

            if CB_LAYER_SELECTED[I] then
                Inc(SelectedCount);
        end;

        if SelectedCount = 0 then
        begin
            ShowMessage('Select at least one copper layer.');
            Exit;
        end;

        CB_PAD_SIZE_MM     := StrToFloat(EdSize.Text);
        CB_PITCH_X_MM      := StrToFloat(EdPitchX.Text);
        CB_PITCH_Y_MM      := StrToFloat(EdPitchY.Text);
        CB_COPPER_CLEAR_MM := StrToFloat(EdCopperClear.Text);
        CB_EDGE_CLEAR_MM   := StrToFloat(EdEdgeClear.Text);

        if RbSquare.Checked then
            CB_PATTERN_TYPE := CB_PATTERN_SQUARE
        else
        begin
            if RbCircle.Checked then
                CB_PATTERN_TYPE := CB_PATTERN_CIRCLE
            else
                CB_PATTERN_TYPE := CB_PATTERN_DIAMOND;
        end;

        CB_GROUP_AS_COMPONENT := ChGroup.Checked;

        Result := True;

    Finally
        F.Free;
    End;
end;


{------------------------------------------------------------------------------}
function MaxCoord(A, B : TCoord) : TCoord;
begin
    if A > B then
        Result := A
    else
        Result := B;
end;


{------------------------------------------------------------------------------}
function HolderExists(AName : String) : Boolean;
var
    It   : IPCB_BoardIterator;
    Comp : IPCB_Component;
begin
    Result := False;

    It := Board.BoardIterator_Create;
    It.AddFilter_ObjectSet(MkSet(eComponentObject));
    It.AddFilter_LayerSet(AllLayers);
    It.AddFilter_Method(eProcessAll);

    Comp := It.FirstPCBObject;
    while Comp <> nil do
    begin
        if Comp.Name.Text = AName then
        begin
            Result := True;
            Break;
        end;
        Comp := It.NextPCBObject;
    end;

    Board.BoardIterator_Destroy(It);
end;


{------------------------------------------------------------------------------}
function CreateHolderComponent(AName : String; ALayer : TLayer) : IPCB_Component;
var
    Comp : IPCB_Component;
begin
    Result := nil;

    Comp := PCBServer.PCBObjectFactory(eComponentObject, eNoDimension, eCreate_Default);
    if Comp = nil then Exit;

    Comp.X := Board.XOrigin;
    Comp.Y := Board.YOrigin;
    Comp.Layer := ALayer;

    Comp.PrimitiveLock := False;
    Comp.Moveable := False;

    Comp.NameOn := False;
    Comp.Name.Text := AName;

    Comp.CommentOn := False;
    Comp.Comment.Text := CB_HOLDER_MARKER;

    Comp.ComponentKind := eComponentKind_Graphical;

    Board.AddPCBObject(Comp);

    PCBServer.SendMessageToRobots(
        Board.I_ObjectAddress,
        c_Broadcast,
        PCBM_BoardRegisteration,
        Comp.I_ObjectAddress
    );

    Result := Comp;
end;


{------------------------------------------------------------------------------}
function PointWithEdgeMarginInsideBoard(X, Y : TCoord) : Boolean;
var
    I        : Integer;
    Angle    : Double;
    Radius   : TCoord;
    PX, PY   : TCoord;
    HalfDiag : TCoord;
begin
    Result := False;

    HalfDiag := MMsToCoord(CB_PAD_SIZE_MM / Sqrt(2.0));
    Radius   := HalfDiag + MMsToCoord(CB_EDGE_CLEAR_MM);

    if not Board.BoardOutline.PointInPolygon(X, Y) then Exit;

    for I := 0 to CB_EDGE_SAMPLES - 1 do
    begin
        Angle := (2.0 * 3.14159265358979323846 * I) / CB_EDGE_SAMPLES;
        PX := X + Round(Radius * Cos(Angle));
        PY := Y + Round(Radius * Sin(Angle));

        if not Board.BoardOutline.PointInPolygon(PX, PY) then Exit;
    end;

    Result := True;
end;


{------------------------------------------------------------------------------}
function CreateCandidatePad(X, Y : TCoord; ALayer : TLayer) : IPCB_Pad;
var
    P        : IPCB_Pad;
    PadCache : TPadCache;
    PadSize  : TCoord;
begin
    Result := nil;

    P := PCBServer.PCBObjectFactory(ePadObject, eNoDimension, eCreate_Default);
    if P = nil then Exit;

    PadSize := MMsToCoord(CB_PAD_SIZE_MM);

    P.Mode := ePadMode_Simple;
    P.X := X;
    P.Y := Y;
    P.Layer := ALayer;

    P.TopXSize := PadSize;
    P.TopYSize := PadSize;

    { Pattern geometry }
    if CB_PATTERN_TYPE = CB_PATTERN_CIRCLE then
    begin
        P.TopShape := eRounded;
        P.Rotation := 0;
    end
    else
    begin
        P.TopShape := eRectangular;

        if CB_PATTERN_TYPE = CB_PATTERN_DIAMOND then
            P.Rotation := 45
        else
            P.Rotation := 0;
    end;

    P.HoleSize := 0;
    P.Name := CB_PAD_MARKER;
    P.Net := nil;

    { Set the cache FIRST.
      Using GetState_Cache / SetState_Cache follows the Altium scripting
      examples and avoids overwriting tenting flags afterwards. }
    PadCache := P.GetState_Cache;

    { Strong negative manual mask expansion is an additional safety net.
      Tenting set below is the authoritative setting. }
    PadCache.SolderMaskExpansion := -PadSize;
    PadCache.SolderMaskExpansionValid := eCacheManual;

    { No paste-mask aperture. }
    PadCache.PasteMaskExpansion := -PadSize;
    PadCache.PasteMaskExpansionValid := eCacheManual;

    P.SetState_Cache(PadCache);

    { IMPORTANT:
      Force tenting AFTER assigning PadCache.
      IsTenting closes both sides; Top/Bottom are set explicitly as well
      because AD exposes independent mask-tenting states. }
    P.IsTenting := True;
    P.IsTenting_Top := True;
    P.IsTenting_Bottom := True;

    P.InvalidateSizeShape;
    P.ValidateSizeShape;

    Result := P;
end;


{------------------------------------------------------------------------------}
function CandidateHasCollision(
    Candidate : IPCB_Pad;
    ALayer    : TLayer;
    CopperRule: IPCB_ClearanceConstraint;
    EdgeRule  : IPCB_ClearanceConstraint
) : Boolean;
var
    Spatial       : IPCB_SpatialIterator;
    Primitive     : IPCB_Primitive;
    Violation     : IPCB_Violation;
    CandidateRect : TCoordRect;
    Layers        : IPCB_LayerSet;
    SearchGap     : TCoord;
begin
    Result := False;

    CandidateRect := Candidate.BoundingRectangle;
    SearchGap := MaxCoord(CopperRule.Gap, EdgeRule.Gap);

    Layers := LayerSet.CreateLayerSet;
    Layers.Include(ALayer);
    Layers.Include(String2Layer('Multi Layer'));
    Layers.Include(String2Layer('Keep Out Layer'));

    Spatial := Board.SpatialIterator_Create;
    Spatial.AddFilter_ObjectSet(AllObjects);
    Spatial.AddFilter_IPCB_LayerSet(Layers);
    Spatial.AddFilter_Area(
        CandidateRect.Left   - SearchGap,
        CandidateRect.Bottom - SearchGap,
        CandidateRect.Right  + SearchGap,
        CandidateRect.Top    + SearchGap
    );

    Primitive := Spatial.FirstPCBObject;

    while Primitive <> nil do
    begin
        if Primitive.I_ObjectAddress <> Candidate.I_ObjectAddress then
        begin
            Violation := nil;

            if Primitive.ObjectId = eRegionObject then
            begin
                if Primitive.Kind = eRegionkind_BoardCutout then
                    Violation := EdgeRule.ActualCheck(Primitive, Candidate)
                else
                    Violation := CopperRule.ActualCheck(Primitive, Candidate);
            end
            else
            begin
                Violation := CopperRule.ActualCheck(Primitive, Candidate);
            end;

            if Violation <> nil then
            begin
                Result := True;
                Break;
            end;
        end;

        Primitive := Spatial.NextPCBObject;
    end;

    Board.SpatialIterator_Destroy(Spatial);
    Layers := nil;
end;


{------------------------------------------------------------------------------}
procedure AttachToHolder(P : IPCB_Pad; Holder : IPCB_Component);
begin
    Holder.AddPCBObject(P);

    PCBServer.SendMessageToRobots(
        Holder.I_ObjectAddress,
        c_Broadcast,
        PCBM_BoardRegisteration,
        P.I_ObjectAddress
    );
end;


{------------------------------------------------------------------------------}
procedure RegisterFreePad(P : IPCB_Pad);
begin
    { In free mode the pad stays directly | layer: the board.
      Under the default Altium Advanced Setting
      PCB.Rules.DeadCopperNoNet = 2, free pads are intentionally
      excluded from the "Dead Copper - Net Not Assigned" DRC report. }
    PCBServer.SendMessageToRobots(
        Board.I_ObjectAddress,
        c_Broadcast,
        PCBM_BoardRegisteration,
        P.I_ObjectAddress
    );
end;


{------------------------------------------------------------------------------}
function GetLayerDisplayName(ALayer : TLayer) : String;
var
    LayerObj : IPCB_LayerObject;
begin
    Result := 'Layer ' + IntToStr(Ord(ALayer));

    if Board.LayerStack = nil then Exit;

    LayerObj := Board.LayerStack.LayerObject[ALayer];

    if LayerObj <> nil then
        Result := LayerObj.Name;
end;


{------------------------------------------------------------------------------}
function EstimateGridPositionsForLayer(ALayer : TLayer) : Integer;
var
    Rect       : TCoordRect;
    X, Y       : TCoord;
    StartX     : TCoord;
    PitchX     : TCoord;
    PitchY     : TCoord;
    Row        : Integer;
    UseStagger : Boolean;
begin
    Result := 0;

    Rect := Board.BoardOutline.BoundingRectangle;

    PitchX := MMsToCoord(CB_PITCH_X_MM);
    PitchY := MMsToCoord(CB_PITCH_Y_MM);

    if PitchX <= 0 then Exit;
    if PitchY <= 0 then Exit;

    UseStagger := False;

    if CB_PATTERN_TYPE = CB_PATTERN_DIAMOND then
        UseStagger := True;

    if CB_PATTERN_TYPE = CB_PATTERN_CIRCLE then
        UseStagger := True;

    Row := 0;
    Y := Rect.Bottom + (PitchY div 2);

    while Y <= Rect.Top do
    begin
        StartX := Rect.Left + (PitchX div 2);

        if UseStagger then
        begin
            if (Row mod 2) = 1 then
                StartX := StartX + (PitchX div 2);
        end;

        X := StartX;

        while X <= Rect.Right do
        begin
            Inc(Result);
            X := X + PitchX;
        end;

        Y := Y + PitchY;
        Inc(Row);
    end;
end;


{------------------------------------------------------------------------------}
procedure GenerateLayer(
    ALayer      : TLayer;
    HolderName  : String;
    CopperRule  : IPCB_ClearanceConstraint;
    EdgeRule    : IPCB_ClearanceConstraint;
    var Added   : Integer;
    var Rejected: Integer
);
var
    Rect        : TCoordRect;
    Holder      : IPCB_Component;
    Candidate   : IPCB_Pad;
    X, Y        : TCoord;
    StartX      : TCoord;
    PitchX      : TCoord;
    PitchY      : TCoord;
    Row         : Integer;
    UseGroup    : Boolean;
    UseStagger  : Boolean;
begin
    SetProgressStatus(
        'Generating: ' + PatternName(0) + ' | layer: ' + GetLayerDisplayName(ALayer)
    );

    Rect := Board.BoardOutline.BoundingRectangle;

    PitchX := MMsToCoord(CB_PITCH_X_MM);
    PitchY := MMsToCoord(CB_PITCH_Y_MM);

    Holder := nil;
    UseGroup := False;

    if CB_GROUP_AS_COMPONENT then
    begin
        if IsOuterLayer(ALayer) then
            UseGroup := True;
    end;

    if UseGroup then
    begin
        Holder := CreateHolderComponent(HolderName, ALayer);

        if Holder = nil then
        begin
            ShowMessage('Could not create holder component: ' + HolderName);
            Exit;
        end;
    end;

    { Squares are aligned. Diamonds and circles are staggered. }
    UseStagger := False;

    if CB_PATTERN_TYPE = CB_PATTERN_DIAMOND then
        UseStagger := True;

    if CB_PATTERN_TYPE = CB_PATTERN_CIRCLE then
        UseStagger := True;

    Row := 0;
    Y := Rect.Bottom + (PitchY div 2);

    while Y <= Rect.Top do
    begin
        StartX := Rect.Left + (PitchX div 2);

        if UseStagger then
        begin
            if (Row mod 2) = 1 then
                StartX := StartX + (PitchX div 2);
        end;

        X := StartX;

        while X <= Rect.Right do
        begin
            if PointWithEdgeMarginInsideBoard(X, Y) then
            begin
                Candidate := CreateCandidatePad(X, Y, ALayer);

                if Candidate <> nil then
                begin
                    Board.AddPCBObject(Candidate);

                    if CandidateHasCollision(
                        Candidate,
                        ALayer,
                        CopperRule,
                        EdgeRule
                    ) then
                    begin
                        Board.RemovePCBObject(Candidate);
                        Inc(Rejected);
                    end
                    else
                    begin
                        if UseGroup then
                            AttachToHolder(Candidate, Holder)
                        else
                            RegisterFreePad(Candidate);

                        Inc(Added);
                    end;
                end;
            end
            else
            begin
                Inc(Rejected);
            end;

            UpdateProgress(1);

            X := X + PitchX;
        end;

        Y := Y + PitchY;
        Inc(Row);
    end;

    if UseGroup then
        Board.ViewManager_GraphicallyInvalidatePrimitive(Holder);
end;


{------------------------------------------------------------------------------}
procedure CollectTaggedFreePads(PadList : TInterfaceList);
var
    It  : IPCB_BoardIterator;
    Pad : IPCB_Pad;
begin
    if PadList = nil then Exit;

    It := Board.BoardIterator_Create;
    if It = nil then Exit;

    Try
        It.AddFilter_ObjectSet(MkSet(ePadObject));
        It.AddFilter_LayerSet(AllLayers);
        It.AddFilter_Method(eProcessAll);

        Pad := It.FirstPCBObject;

        while Pad <> nil do
        begin
            if Pad.Name = CB_PAD_MARKER then
            begin
                { Only free pads generated in normal non-grouped mode. }
                if Pad.InComponent = False then
                    PadList.Add(Pad);
            end;

            Pad := It.NextPCBObject;
        end;

    Finally
        Board.BoardIterator_Destroy(It);
    End;
end;


{------------------------------------------------------------------------------}
procedure CollectMarkedHolders(HolderList : TInterfaceList);
var
    It   : IPCB_BoardIterator;
    Comp : IPCB_Component;
begin
    if HolderList = nil then Exit;

    It := Board.BoardIterator_Create;
    if It = nil then Exit;

    Try
        It.AddFilter_ObjectSet(MkSet(eComponentObject));
        It.AddFilter_LayerSet(AllLayers);
        It.AddFilter_Method(eProcessAll);

        Comp := It.FirstPCBObject;

        while Comp <> nil do
        begin
            if Comp.Comment.Text = CB_HOLDER_MARKER then
                HolderList.Add(Comp);

            Comp := It.NextPCBObject;
        end;

    Finally
        Board.BoardIterator_Destroy(It);
    End;
end;


{------------------------------------------------------------------------------}
procedure RemoveCollectedPads(
    PadList          : TInterfaceList;
    var RemovedCount : Integer
);
var
    I   : Integer;
    Pad : IPCB_Pad;
begin
    if PadList = nil then Exit;

    SetProgressStatus('Removing free balancing elements...');

    for I := 0 to PadList.Count - 1 do
    begin
        Pad := PadList.Items[I];

        if Pad <> nil then
        begin
            Board.RemovePCBObject(Pad);

            { Register deletion with the PCB/Undo system. }
            PCBServer.SendMessageToRobots(
                Board.I_ObjectAddress,
                c_Broadcast,
                PCBM_BoardRegisteration,
                Pad.I_ObjectAddress
            );

            Inc(RemovedCount);
            UpdateProgress(1);
        end;
    end;
end;


{------------------------------------------------------------------------------}
procedure RemoveCollectedHolders(
    HolderList       : TInterfaceList;
    var RemovedCount : Integer
);
var
    I    : Integer;
    Comp : IPCB_Component;
begin
    if HolderList = nil then Exit;

    SetProgressStatus('Removing grouped balancing elements...');

    for I := 0 to HolderList.Count - 1 do
    begin
        Comp := HolderList.Items[I];

        if Comp <> nil then
        begin
            Board.RemovePCBObject(Comp);

            PCBServer.SendMessageToRobots(
                Board.I_ObjectAddress,
                c_Broadcast,
                PCBM_BoardRegisteration,
                Comp.I_ObjectAddress
            );

            Inc(RemovedCount);
            UpdateProgress(1);
        end;
    end;
end;


{------------------------------------------------------------------------------}
procedure RemoveCopperBalance;
var
    RemovedFreePads : Integer;
    RemovedHolders  : Integer;
    TotalToRemove   : Integer;
    PadList         : TInterfaceList;
    HolderList      : TInterfaceList;
begin
    Board := PCBServer.GetCurrentPCBBoard;

    if Board = nil then
    begin
        ShowMessage('Open a PCB document first.');
        Exit;
    end;

    RemovedFreePads := 0;
    RemovedHolders  := 0;

    PadList := TInterfaceList.Create;
    HolderList := TInterfaceList.Create;

    Try
        { IMPORTANT:
          Scan the PCB only once for pads and once for holders.
          Objects are collected first, iterators are destroyed, and only then
          are the objects removed. This is the deletion method recommended by
          Altium for PCB iterators and changes the old O(n^2)-like removal
          behavior into essentially O(n). }
        CollectTaggedFreePads(PadList);
        CollectMarkedHolders(HolderList);

        TotalToRemove := PadList.Count + HolderList.Count;

        if TotalToRemove = 0 then
        begin
            ShowMessage('No generated Copper Balancing elements were found.');
            Exit;
        end;

        ShowProgressWindow(
            'Copper Balancing - Removing',
            'Removing generated balancing elements...',
            TotalToRemove
        );

        PCBServer.PreProcess;
        Try
            RemoveCollectedPads(PadList, RemovedFreePads);
            RemoveCollectedHolders(HolderList, RemovedHolders);

            FinishProgress(0);
        Finally
            PCBServer.PostProcess;
            CloseProgressWindow(0);
        End;

    Finally
        PadList.Free;
        HolderList.Free;
    End;

    Board.ViewManager_FullUpdate;

    ResetParameters;
    AddStringParameter('Action', 'Redraw');
    RunProcess('PCB:Zoom');

    ShowMessage(
        'Copper Balancing was removed from all layers.' + #13#10 + #13#10 +
        'Free elements removed: ' + IntToStr(RemovedFreePads) + #13#10 +
        'Grouped holders removed: ' + IntToStr(RemovedHolders)
    );
end;


{------------------------------------------------------------------------------}
procedure Start;
var
    CopperRule      : IPCB_ClearanceConstraint;
    EdgeRule        : IPCB_ClearanceConstraint;
    Added           : Integer;
    Rejected        : Integer;
    TotalAdded      : Integer;
    TotalRejected   : Integer;
    SelectedLayers  : Integer;
    TotalGridSteps  : Integer;
    I               : Integer;
    HolderName      : String;
    DialogAccepted  : Boolean;
begin
    Board := PCBServer.GetCurrentPCBBoard;

    if Board = nil then
    begin
        ShowMessage('Open a PCB document first.');
        Exit;
    end;

    InitDefaults(0);

    Try
        DialogAccepted := ShowSettingsDialog(0);
    Except
        ShowMessage(
            'One of the numeric values is invalid.' + #13#10 +
            'Use the decimal separator configured in Windows.'
        );
        Exit;
    End;

    if CB_REMOVE_REQUESTED then
    begin
        RemoveCopperBalance;
        Exit;
    end;

    if not DialogAccepted then
        Exit;

    if CB_PAD_SIZE_MM <= 0 then
    begin
        ShowMessage('Element size must be greater than zero.');
        Exit;
    end;

    if CB_PITCH_X_MM <= 0 then
    begin
        ShowMessage('Horizontal spacing X must be greater than zero.');
        Exit;
    end;

    if CB_PITCH_Y_MM <= 0 then
    begin
        ShowMessage('Vertical spacing Y must be greater than zero.');
        Exit;
    end;

    if CB_COPPER_CLEAR_MM < 0 then
    begin
        ShowMessage('Copper clearance cannot be negative.');
        Exit;
    end;

    if CB_EDGE_CLEAR_MM < 0 then
    begin
        ShowMessage('Board edge clearance cannot be negative.');
        Exit;
    end;

    TotalAdded := 0;
    TotalRejected := 0;
    SelectedLayers := 0;
    TotalGridSteps := 0;

    { Calculate progress maximum before modifying the PCB. }
    for I := 0 to CB_LAYER_COUNT - 1 do
    begin
        if CB_LAYER_SELECTED[I] then
        begin
            TotalGridSteps :=
                TotalGridSteps +
                EstimateGridPositionsForLayer(CB_LAYER_IDS[I]);

            Inc(SelectedLayers);
        end;
    end;

    ShowProgressWindow(
        'Copper Balancing - Generating',
        'Preparing generation...',
        TotalGridSteps
    );

    CopperRule := nil;
    EdgeRule := nil;

    PCBServer.PreProcess;
    Try
        CopperRule := PCBServer.PCBRuleFactory(eRule_Clearance);
        CopperRule.Scope1Expression := 'All';
        CopperRule.Scope2Expression := 'All';
        CopperRule.NetScope := eNetScope_AnyNet;
        CopperRule.Name := '__CB_TEMP_COPPER_CLEARANCE__';
        CopperRule.Comment := 'Temporary rule created by CopperBalancing';
        CopperRule.Gap := MMsToCoord(CB_COPPER_CLEAR_MM);
        Board.AddPCBObject(CopperRule);

        EdgeRule := PCBServer.PCBRuleFactory(eRule_Clearance);
        EdgeRule.Scope1Expression := 'All';
        EdgeRule.Scope2Expression := 'All';
        EdgeRule.NetScope := eNetScope_AnyNet;
        EdgeRule.Name := '__CB_TEMP_EDGE_CLEARANCE__';
        EdgeRule.Comment := 'Temporary rule created by CopperBalancing';
        EdgeRule.Gap := MMsToCoord(CB_EDGE_CLEAR_MM);
        Board.AddPCBObject(EdgeRule);

        for I := 0 to CB_LAYER_COUNT - 1 do
        begin
            if CB_LAYER_SELECTED[I] then
            begin
                Added := 0;
                Rejected := 0;

                HolderName := 'CBAL_' + IntToStr(Ord(CB_LAYER_IDS[I]));

                GenerateLayer(
                    CB_LAYER_IDS[I],
                    HolderName,
                    CopperRule,
                    EdgeRule,
                    Added,
                    Rejected
                );

                TotalAdded := TotalAdded + Added;
                TotalRejected := TotalRejected + Rejected;
            end;
        end;

        FinishProgress(0);

    Finally
        if CopperRule <> nil then
            Board.RemovePCBObject(CopperRule);

        if EdgeRule <> nil then
            Board.RemovePCBObject(EdgeRule);

        PCBServer.PostProcess;
        CloseProgressWindow(0);
    End;

    ResetParameters;
    AddStringParameter('Action', 'Redraw');
    RunProcess('PCB:Zoom');

    ShowMessage(
        'Copper Balancing generation completed.' + #13#10 + #13#10 +
        'Pattern: ' + PatternName(0) + #13#10 +
        'Layers processed: ' + IntToStr(SelectedLayers) + #13#10 +
        'Elements added: ' + IntToStr(TotalAdded) + #13#10 +
        'Skipped positions: ' + IntToStr(TotalRejected) + #13#10 + #13#10 +
        'Before release, run DRC and inspect Gerber/ODB++ output.'
    );
end;
